service:
  name: rate-my-products-backend

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-central-1'}
  apiGateway:
    shouldStartNameWithService: true

  environment:
    PRODUCTS_TABLE: Products-${self:provider.stage}
    #RATINGS_TABLE: Ratings-${self:provider.stage}
    USER_RATINGS_TABLE: User-Ratings-${self:provider.stage}
    PRODUCT_INDEX_BY_USERID: ProductsByUserId
    PRODUCT_IMAGES_S3_BUCKET: megustacc-products-images-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300
    AUTH_0_JWKS_URL: https://dev-lb67h78z.eu.auth0.com/.well-known/jwks.json

  tracing:
    lambda: true
    apiGateway: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'

custom:
  documentation:
    api:
      info:
        version: v0.0.1
        title: Serverless product rating API
        description: Serverless API for rating products
    models:
      - name: CreateProductRequest
        contentType: application/json
        schema: ${file(models/create-product-request.json)}
      - name: CreateRatingRequest
        contentType: application/json
        schema: ${file(models/create-rating-request.json)}
      - name: UpdateRatingRequest
        contentType: application/json
        schema: ${file(models/update-rating-request.json)}

functions:
  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetProducts:
    handler: src/lambda/http/product/getProducts.handler
    events:
      - http:
          method: get
          authorizer: Auth
          path: products
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

  GetProduct:
    handler: src/lambda/http/product/getProduct.handler
    events:
      - http:
          method: get
          authorizer: Auth
          path: products/{productId}
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:getItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

  CreateProduct:
    handler: src/lambda/http/product/createProduct.handler
    events:
      - http:
          method: post
          authorizer: Auth
          path: products
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: "Create new Product"
            description: "Create new Product"
            requestModels:
              "application/json": CreateProductRequest
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:putItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

  DeleteProduct:
    handler: src/lambda/http/product/deleteProduct.handler
    events:
      - http:
          method: delete
          authorizer: Auth
          path: products/{productId}
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:Scan
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}

  GenerateUploadUrl:
    handler: src/lambda/http/product/generateUploadUrl.handler
    events:
      - http:
          method: post
          authorizer: Auth
          path: products/{productId}/attachment
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource: arn:aws:s3:::${self:provider.environment.PRODUCT_IMAGES_S3_BUCKET}/*
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

  GetAllRatings:
    handler: src/lambda/http/rating/getRatings.handler
    events:
      - http:
          method: get
          authorizer: Auth
          path: products/ratings
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}

  GetUserRatings:
    handler: src/lambda/http/rating/getUserRatings.handler
    events:
      - http:
          method: get
          authorizer: Auth
          path: products/ratings/self
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}

  GetProductRatings:
    handler: src/lambda/http/rating/getProductRatings.handler
    events:
      - http:
          method: get
          authorizer: Auth
          path: products/{productId}/ratings
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
          - dynamodb:Query
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}/index/${self:provider.environment.PRODUCT_INDEX_BY_USERID}

  CreateRating:
    handler: src/lambda/http/rating/createRating.handler
    events:
      - http:
          method: post
          authorizer: Auth
          path: products/{productId}/ratings
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: "Create new Rating"
            description: "Create new Rating"
            requestModels:
              "application/json": CreateRatingRequest
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:putItem
          - dynamodb:Query
          - dynamodb:GetItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}/index/${self:provider.environment.PRODUCT_INDEX_BY_USERID}
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}

  UpdateRating:
    handler: src/lambda/http/rating/updateRating.handler
    events:
      - http:
          method: patch
          authorizer: Auth
          path: products/ratings/{ratingId}
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: "Update Rating"
            description: "Update Rating"
            requestModels:
              "application/json": UpdateRatingRequest
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}

  DeleteRating:
    handler: src/lambda/http/rating/deleteRating.handler
    events:
      - http:
          method: delete
          authorizer: Auth
          path: products/ratings/{ratingId}
          cors: true
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource:
          - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USER_RATINGS_TABLE}



resources:
  Resources:
    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.PRODUCTS_TABLE}

    UserRatingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: ratingId
            AttributeType: S
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: ratingId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.USER_RATINGS_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.PRODUCT_INDEX_BY_USERID}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: productId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL # What attributes will be copied to an index

    ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PRODUCT_IMAGES_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: PublicReadObject
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: 'arn:aws:s3:::${self:provider.environment.PRODUCT_IMAGES_S3_BUCKET}/*'
        Bucket: !Ref ImageBucket